import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.2';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { dataset_id } = await req.json();

    if (!dataset_id) {
      return Response.json({ error: 'dataset_id is required' }, { status: 400 });
    }

    // Fetch key metrics
    const metrics = await base44.asServiceRole.entities.MetricSnapshot.filter({ dataset_id });
    const dataset = await base44.asServiceRole.entities.DataUpload.get(dataset_id);
    const execSummary = await base44.asServiceRole.entities.ReportSection.filter({ 
      dataset_id, 
      section_id: 0 
    });

    // Get key metrics
    const activeRatio = metrics.find(m => m.metric_key === 'active_ratio')?.value_num || 0;
    const coreDriverRatio = metrics.find(m => m.metric_key === 'core_driver_ratio')?.value_num || 0;
    const top10Share = metrics.find(m => m.metric_key === 'top10_share')?.value_num || 0;
    const approvalRate = metrics.find(m => m.metric_key === 'avg_approval_rate')?.value_num || 0;

    // Generate one-page PDF
    const doc = new jsPDF();
    let y = 25;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text('Board Summary', 20, y);
    y += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Affiliate Growth Intelligence Dashboard - ${new Date().toLocaleDateString()}`, 20, y);
    y += 15;

    // Key Metrics Box
    doc.setFillColor(249, 250, 251);
    doc.rect(15, y, 180, 50, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(15, y, 180, 50, 'S');

    // Metrics in grid
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    
    // Row 1
    doc.text('Active Ratio', 20, y + 8);
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`${(activeRatio * 100).toFixed(1)}%`, 20, y + 18);
    
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text('Core Driver Ratio', 65, y + 8);
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`${(coreDriverRatio * 100).toFixed(1)}%`, 65, y + 18);

    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text('Top 10 Concentration', 115, y + 8);
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`${(top10Share * 100).toFixed(1)}%`, 115, y + 18);

    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text('Approval Rate', 165, y + 8);
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`${(approvalRate * 100).toFixed(1)}%`, 165, y + 18);

    // Status indicators
    doc.setFontSize(7);
    y += 28;
    
    const statusColor = activeRatio > 0.5 ? [34, 197, 94] : [234, 179, 8];
    doc.setTextColor(...statusColor);
    doc.text(activeRatio > 0.5 ? '✓ Healthy' : '⚠ Monitor', 20, y);
    
    const coreColor = coreDriverRatio > 0.15 ? [34, 197, 94] : [234, 179, 8];
    doc.setTextColor(...coreColor);
    doc.text(coreDriverRatio > 0.15 ? '✓ Strong' : '⚠ Improve', 65, y);
    
    const concColor = top10Share < 0.7 ? [34, 197, 94] : [234, 179, 8];
    doc.setTextColor(...concColor);
    doc.text(top10Share < 0.7 ? '✓ Balanced' : '⚠ High Risk', 115, y);
    
    const apprColor = approvalRate > 0.85 ? [34, 197, 94] : [234, 179, 8];
    doc.setTextColor(...apprColor);
    doc.text(approvalRate > 0.85 ? '✓ Good' : '⚠ Check', 165, y);

    y += 20;

    // Executive Summary
    if (execSummary.length > 0) {
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text('Executive Summary', 20, y);
      y += 8;

      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      const conclusion = execSummary[0].conclusion || 'No summary available';
      const lines = doc.splitTextToSize(conclusion, 170);
      doc.text(lines, 20, y);
      y += lines.length * 5 + 10;

      // Key findings
      if (execSummary[0].key_findings && execSummary[0].key_findings.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text('Key Findings & Priorities', 20, y);
        y += 7;

        doc.setFontSize(8);
        doc.setTextColor(51, 65, 85);
        execSummary[0].key_findings.slice(0, 5).forEach((finding) => {
          const text = typeof finding === 'string' ? finding : (finding.text || '');
          const lines = doc.splitTextToSize(`• ${text}`, 165);
          doc.text(lines, 25, y);
          y += lines.length * 4 + 2;
        });
      }
    }

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by Affiliate Growth Intelligence Dashboard', 20, 285);

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Board-Summary-${dataset.version_label || 'latest'}.pdf"`
      }
    });

  } catch (error) {
    console.error('Board summary generation error:', error);
    return Response.json({ 
      error: error.message,
      details: 'Failed to generate board summary'
    }, { status: 500 });
  }
});